### ISSUE TITLE
messageSecurity-trustStore.jks File non esistente

### ISSUE THREAD

**Issue by nicolabeghin** [link-it/govway-docker#10]
Buonasera
testando erogazione MODI riscontriamo il seguente errore 

> Riscontrato errore durante la validazione sintattica della busta ricevuta:
[ErroreInterno]: org.openspcoop2.protocol.sdk.ProtocolException: TrustStore Certificati [/etc/govway/modipa/messageSecurity-trustStore.jks] File non esistente

E' necessario creare manualmente il keystore in fase di creazione dell'immagine Docker o è un errore differente? In caso sia necessario crearlo, è possibile fornire indicazioni al riguardo?

grazie
nicola

**Comment by andreapoli** [comment]
Buongiorno Nicola,

il truststore deve essere creato; trovi informazioni a riguardo nella sezione [Trust tra fruitore ed erogatore tramite certificati X509](https://govway.org/documentazione/console/profiloModIPA/messaggio/passiPreliminari/trustStoreX509.html) della documentazione.

Per farlo puoi rendere persistente una location (es./etc/govway) montando un volume. 
Esempio:

```
docker run \
....
 -v ~/govway_conf:/etc/govway \
....
linkitaly/govway
```

Puoi trovare esempi completi nella [home page di GovWay su dockerhub](https://hub.docker.com/r/linkitaly/govway).
