### ISSUE TITLE
errore avvio docker image su Aruba Cloud Application Platform

### ISSUE THREAD

**Issue by endmax** [link-it/govway-docker#14]
Non riesco a far partire un'istanza dell'immagine [3.3.15.p2_standalone](https://github.com/link-it/govway-docker/blob/gw_3.3.15.p2/govway/tomcat9/Dockerfile.govway) in [Aruba Cloud Application Platform](https://www.arubacloud.com/application-platform/caas-container-as-a-service.aspx)
Questi il log:
[run.log](https://github.com/user-attachments/files/17713883/run.log)
[bootstrap.log](https://github.com/user-attachments/files/17713900/bootstrap.log)
[dpkg.log](https://github.com/user-attachments/files/17713915/dpkg.log)
[alternatives.log](https://github.com/user-attachments/files/17713978/alternatives.log)
[jem.log](https://github.com/user-attachments/files/17713966/jem.log)

**Comment by marklar79** [comment]
Buonasera,

potreste recuperare il file /tmp/entrypoint_debug.log dal container che non si avvia ?
Inoltre potrebbe essere utile esaminare i files di log generati in fase di avvio. Dovreste trovarli al path /var/log/govway

**Comment by endmax** [comment]
Ciao,

nel entrypoint_debug.log allegato ho trovato questo errore:
`Riscontrato errore durante l'inizializzazione della configurazione di OpenSPCoop.`
[entrypoint_debug.log](https://github.com/user-attachments/files/17729837/entrypoint_debug.log)

**Comment by endmax** [comment]
Ecco gli altri log:
[govway_core.log](https://github.com/user-attachments/files/17729867/govway_core.log)
[catalina.2024-11-12.log](https://github.com/user-attachments/files/17729910/catalina.2024-11-12.log)
[govway_console_core.log](https://github.com/user-attachments/files/17729920/govway_console_core.log)
[govway_controlloTraffico.log](https://github.com/user-attachments/files/17729923/govway_controlloTraffico.log)

**Comment by marklar79** [comment]
> Ecco gli altri log: [govway_core.log](https://github.com/user-attachments/files/17729867/govway_core.log) [catalina.2024-11-12.log](https://github.com/user-attachments/files/17729910/catalina.2024-11-12.log) [govway_console_core.log](https://github.com/user-attachments/files/17729920/govway_console_core.log) [govway_controlloTraffico.log](https://github.com/user-attachments/files/17729923/govway_controlloTraffico.log)

non vedo il file: /var/log/govway/govway_startup.log per caso non è stato generato ?

**Comment by endmax** [comment]
si c'è. Mi erano sfuggiti tutti questi.
[govway_monitor_core.log](https://github.com/user-attachments/files/17730333/govway_monitor_core.log)
[govway_monitor_core-jcs.log](https://github.com/user-attachments/files/17730334/govway_monitor_core-jcs.log)
[govway_startup.log](https://github.com/user-attachments/files/17730335/govway_startup.log)
[govway_timers.log](https://github.com/user-attachments/files/17730336/govway_timers.log)
[localhost.2024-11-12.log](https://github.com/user-attachments/files/17730337/localhost.2024-11-12.log)
[localhost_access_log.2024-11-12.log](https://github.com/user-attachments/files/17730338/localhost_access_log.2024-11-12.log)

**Comment by marklar79** [comment]
Buonasera @endmax ,

il problema si verifica a causa di una particolarità dell'ambiente Application Platform di Aruba che è implementato tramite Virtuozzo.
In questo ambiente le schede di rete agganciate alla VPS/container non hanno un MAC address associato; il valore del MAC address viene utilizzato da GovWay per la generazione degli UUID delle transazioni, e viene letto in fase di avvio. La mancanza  di questo valore rappresenta per GovWay un errore non recuperabile.

Per il momento puoi rimediare al problema creando il file /etc/govway/govway_local.properties nella VPS/container e inserire la seguente proprietà:
```
org.openspcoop2.pdd.idGenerator=UUIDv4sec
```
In questo modo viene utilizzato un'algoritmo differente per la generazione degli UUID che non fà uso del MAC address.

Nelle prossime release renderemo la proprietà configurabile tramite variabile d'ambiente, in modo da poter gestire più facilmente gli ambienti che hanno questa peculiarità (Virtuozzo).

**Comment by endmax** [comment]
Grazie Andrea. Funziona.

piccolo appunto: il file va in /etc/govway.

**Comment by marklar79** [comment]
Hai ragione. Ho corretto direttamente sul commento originale.
Chiudo la Issue.

**Comment by andreapoli** [comment]
Buongiorno @endmax le versioni snapshot prodotte nell'ambiente di [continuous integration](https://jenkins.link.it/govway/job/GovWay/) consentono adesso di impostare l'algoritmo di generazione degli UUID tramite una variabile 'GOVWAY_UUID_ALG' descritta nella [sezione 'configurazioni-avanzate'](https://github.com/link-it/govway-docker#configurazioni-avanzate) della documentazione del repository [govway-docker](https://github.com/link-it/govway-docker).

[master_standalone](https://hub.docker.com/layers/linkitaly/govway/master_standalone/images/sha256-ca64120f6dd6348b3565e397b03d523414911bcc373f275092273a7f5078afd5)
[master_oracle](https://hub.docker.com/layers/linkitaly/govway/master_oracle/images/sha256-6fd09e02f7ca450b0412d09f984d65c1d0836000760a1b4a15a6004e513de91b)
[master_postgresql](https://hub.docker.com/layers/linkitaly/govway/master_postgres/images/sha256-c6244121a2e040adf6d621804c886b650bec0c8f8b34650b77f8372d21fd0cea)

Le immagini relative alla prossima versione di GovWay consentiranno di scegliere l'algoritmo tramite questa variabile.
