### ISSUE TITLE
scelta destinazione Logging

### ISSUE THREAD

**Issue by andesonik** [link-it/govway-docker#15]
Nel nostro ambiente abbiamo fluentbit che si occupa di raccogliere i container log e li invia ad elastic per l'archiviazione e consultazione ma l'applicazione scrive tutti i log su file locali dentro la cartella /var/log/govway.
Verificando i vari file di configurazione log4j2.properties e logging.properties, sono tutti configurati per scrivere su file.
Ci sarebbe un modo per estendere la destinazione di tutti i log verso lo stdout/sterr?
è prevista una implementazione di una variabile d'ambiente per poter gestire gli Appenders di log4j?

**Comment by marklar79** [comment]
Attualmente, tutti i log presenti nella directory /var/log/govway sono log applicativi di debug dell'applicazione, mentre le tracce delle richieste vengono registrate nel database e sono consultabili tramite le console e le API di monitoraggio.

Per registrare le tracce delle richieste su stdout, potete attivare la funzionalità [fileTrace](https://govway.org/documentazione/console/configurazione/tracciamento/fileTrace/index.html) . 
Questo vi permetterà di creare un "access log" personalizzato per le vostre esigenze, a cui però dovete associare un ConsoleAppender per inviare i dati direttamente su STDOUT.

Se itenete assolutamente necessario redirigere tutti i log applicativi di debug, dovrete creare dei file di personalizzazione nella directory /etc/govway, uno per ogni file di configurazione dei log presente negli archivi di Govway. 

Ad esempio, per modificare le impostazioni relative alle category definite in govway.ear/properties/govway.log4j2.properties, sarà necessario creare un file chiamato govway_local.log4j2.properties nella directory /etc/govway. 

Questo file dovrà contenere esclusivamente la ridefinizione degli appender per ciascuna category che desiderate reindirizzare verso STDOUT.
