### ISSUE TITLE
Errore in aggiornamento database da container

### ISSUE THREAD

**Issue by ilkosta** [link-it/govway-docker#3]
Buongiorno, 
avevo installato un ambiente di test di govway 3.3.4p2 tramite script di creazione del docker-compose impostando un database postgres13.

Ho provato ad impostare un nuovo compose per orchestrare l'avvio della versione 3.3.5 (`linkitaly/govway:3.3.5_postgres`) sul db creato dalla versione 3.3.4p2 e mi sarei aspettato l'esecuzione degli script di aggiornamento (es. [script db](https://github.com/link-it/govway/blob/master/resources/sql_upgrade/upgrade_3.3.4_to_3.3.5/postgresql/2021-07-27-configurazionePdD-patch.sql), [proprieta' per modi](https://github.com/link-it/govway/blob/master/resources/properties_upgrade/upgrade_3.3.4_to_3.3.5/protocolli/modipa_local.2021-09-15.diff) ) invece ottengo il seguente log in fase di avvio:

```
govway-3.3.5_postgres | INFO: Readyness base dati TRAC ... inizializzazione avviata.
govway-3.3.5_postgres | SqlTool v. 6266.
govway-3.3.5_postgres | JDBC Connection established to a PostgreSQL v. 13.4 (Debian 13.4-4.pgdg110+1) database
govway-3.3.5_postgres | as "govway" with R/W TRANSACTION_READ_COMMITTED Isolation.
govway-3.3.5_postgres | SqlFile processor v. 6266.
govway-3.3.5_postgres | Distribution is permitted under the terms of the HSQLDB license.
govway-3.3.5_postgres | (c) 2004-2011 Blaine Simpson and the HSQL Development Group.
govway-3.3.5_postgres |
govway-3.3.5_postgres |     \q    to Quit.
govway-3.3.5_postgres |     \?    lists Special Commands.
govway-3.3.5_postgres |     :?    lists Edit-Buffer/History commands.
govway-3.3.5_postgres |     *?    lists PL commands.
govway-3.3.5_postgres |     /?    displays help on how to set and use macros (incl. functions).
govway-3.3.5_postgres |
govway-3.3.5_postgres | SPECIAL Commands begin with '\' and execute when you hit ENTER.
govway-3.3.5_postgres | EDIT-BUFFER / HISTORY Commands begin with ':' and execute when you hit ENTER.
govway-3.3.5_postgres | PROCEDURAL LANGUAGE commands begin with '*' and end when you hit ENTER.
govway-3.3.5_postgres | MACRO executions and definitions begin with '/' and end when you hit ENTER.
govway-3.3.5_postgres | All other lines comprise SQL Statements (or comments).
govway-3.3.5_postgres |   SQL Statements are terminated by either unquoted ';' (which executes the
govway-3.3.5_postgres |   statement), or a blank line (which moves the statement into the edit buffer
govway-3.3.5_postgres |   without executing).
govway-3.3.5_postgres | After turning on variable expansion with command "*" (or any other PL
govway-3.3.5_postgres | command), PL variables may be used in most commands like so:  *{PLVARNAME}.
govway-3.3.5_postgres | Be aware when using regular expressions on commands, that the regex.s
govway-3.3.5_postgres | operate only on the command text after the * or \ prefix, if any.
govway-3.3.5_postgres |
pg_1   | 2021-11-30 10:53:44.788 GMT [43] WARNING:  there is already a transaction in progress
pg_1   | 2021-11-30 10:53:44.804 GMT [43] ERROR:  relation "seq_msgdiagnostici" already exists
pg_1   | 2021-11-30 10:53:44.804 GMT [43] STATEMENT:  CREATE SEQUENCE seq_msgdiagnostici start 1 increment 1 maxvalue 9223372036854775807 minvalue 1 cache 1 CYCLE
govway-3.3.5_postgres | sql> sql> sql>
govway-3.3.5_postgres | INFO: Readyness base dati TRAC ... inizializzazione fallita.
```
ed in seguito all'errore il contenuto di `db_info` e' 

```
govwaydb-# ;
 major_version | minor_version |             notes             | id 
---------------+---------------+-------------------------------+----
             3 |             3 | [3.3.4.p2] Database di GovWay |  1
(1 row)
```
Qual'e' la procedura corretta per aggiornare un database da container?

**Comment by marklar79** [comment]
Salve,

Rispetto alla versione precedente abbiamo introdotto diverse novità, sia dal punto di visto del software utilizzato ( passaggio da tomcat 9 a wildfly 18) sia nella configurabilità dell'immmagine; ti invito a leggere la documentazione su https://github.com/link-it/govway-docker/blob/master/README.md per maggiori informazioni.

Al momento l'immagine non prevede la possibilità di aggiornarsi automaticamente  da una versione precedente; questo non è possibile neanche utilizzando l'installer manualmente, dove invece è previsto di seguire le indicazioni alla URL https://govway.org/documentazione/installazione/dispiegamento/aggiornamento/index.html

Tanto premesso, se vuoi puoi provare a procedere manualmente, puoi provare a seguire questa procedura:

1. Esegui sul database le seguenti istruzioni SQL:
```sql
DELETE FROM db_info;
DELETE FROM db_info_console;
INSERT INTO db_info_console (major_version,minor_version,notes) VALUES (3,3,'[3.3.5] Database della Console di Gestione di GovWay');
INSERT INTO db_info (major_version,minor_version,notes) VALUES (3,3,'[3.3.5] Informazioni Statistiche sulle richieste gestite da GovWay');
INSERT INTO db_info (major_version,minor_version,notes) VALUES (3,3,'[3.3.5] Archivio delle tracce e dei messaggi diagnostici emessi da GovWay');
INSERT INTO db_info (major_version,minor_version,notes) VALUES (3,3,'[3.3.5] Database di GovWay');
UPDATE registri SET location='java:/org.govway.datasource.console';
UPDATE audit_appender_prop SET value='java:/org.govway.datasource.console' WHERE name='datasource';

```
2. Esequi sul database utilizzato da govway, la patch SQL https://github.com/link-it/govway/blob/master/resources/sql_upgrade/upgrade_3.3.4_to_3.3.5/postgresql/2021-07-27-configurazionePdD-patch.sql

3. Se stai montando /var/govway su un volume, dovresti modifcare la configurazione in modo che vengano utilizzati i seguenti due volumi:
```yaml
    volumes:
      - ./govway_conf:/etc/govway
      - ./govway_log:/var/log/govway
  ```
4. Puoi appendere sul file /etc/govway/modipa_local.properties la seguente riga:
 org.openspcoop2.protocol.modipa.generazioneTracce.registrazioneToken.enabled=false


Ovviamente ti consiglio di effetuare un backup del database, prima di procedere.

**Comment by ilkosta** [comment]
grazie @marklar79. 
E' possibile invece procedere solo con backup del database, aggiornamento tramite gli script indicati (1,2) e avvio dei nuovi container? ci sono controindicazioni che ignoro?

**Comment by marklar79** [comment]
Se non ho capito male la domanda, vorresti saltare i punti (3) e (4) della procedura che ti ho indicato.

per il punto (3) dipende tutto dalla tua attuale installazione. Se in precedenza, non utilizzavi il volume montato su /var/govway chiaramente non ci sono problemi; in caso contrario, saltare la modifica significa che i file di properties ed i log saranno accessibili solo internamente, e quindi la loro esistenza sara' legata a quella del container (rischi di perderli se il container viene cancellato).

per il punto (4) non ci sono problemi a saltarlo perche' se non indicata la proprieta' ha per default il valore "false"

**Comment by marklar79** [comment]
Chiudo la Issue in assenza di ulteriori riscontri da parte dell'utente
