### ISSUE TITLE
Accesso al DB dal Container GovWay

### ISSUE THREAD

**Issue by tflagella** [link-it/govway-docker#4]
Vista la criticità delle potenziali operazioni di modifica al DB effettuate in automatico allo startup del container, propongo di:

1) modificare il default della variabile GOVWAY_READY_DB_CHECK_SKIP da 'false' a 'true';

2) perfezionare il controllo sulle tabelle db_info in modo che, nel caso in cui GOVWAY_READY_DB_CHECK_SKIP sia 'false', l'inizializzazione avvenga solo se il DB risulta vuoto e non se la versione risulta diversa da quella del container.

**Comment by marklar79** [comment]
Modifiche apportate al commit 68471fa
