### ISSUE TITLE
assenza di file di properties in /etc/govway

### ISSUE THREAD

**Issue by ilkosta** [link-it/govway-docker#6]
buongiorno, 
avviando (con successo) il container linkitaly/govway:3.3.6_postgres noto che mancano i file di properties nella directory /etc/govway, anche se questa non e' collegato ad un volume. E' normale? sono stati spostati?

**Comment by andreapoli** [comment]
Dalla versione 3.3.5.p2 sono state introdotte diverse novità, sia dal punto di visto del software utilizzato ( passaggio da tomcat 9 a wildfly 18) sia nella configurabilità dell'immmagine.
Per quanto riguarda la directory di configurazione /etc/govway non è più obbligatoria la presenza dei file di configurazione esterni e se non presenti vengono utilizzati i valori di default.
Puoi sempre associare un volume esterno alla directory /etc/govway se hai necessità di ridefinire qualche parametro. Trovi degli esempi sulla [pagina docker-hub di GovWay](https://hub.docker.com/r/linkitaly/govway).
Maggiori informazioni sulle modalità di costruzione delle immagini sono invece presenti nella documentazione sulla home del progetto [govway-docker](https://github.com/link-it/govway-docker/blob/master/README.md).
