### ISSUE TITLE
Assenza HelmChart e log locali

### ISSUE THREAD

**Issue by alex85asr** [link-it/govway-docker#7]
Salve,

nelle cartella del GovWay, versione 3.3.7 è presente una cartella helm, ma all'interno non vedo il chart, ma vedo solo un readme, come mai non c'è?

In seguito all'installazione della stessa versione, vorrei capire se i log che vengono scritti localmente, è possibile inserirli altrove, come ad esempio un elasticsearch e scriverli quindi anche in modalità json.

Grazie,

Alessio

**Comment by marklar79** [comment]
Salve @alex85asr 

1. la cartella helm è stata committata per errore sul repository (sto provvedendo ad eliminarla). Al momento, anche se abbiamo testato alcuni scenari di deploy tramite chart helm, non abbiamo ancora rilasciato nulla dato che non li riteniamo ancora abbastanza generici da essere utilizzati in contesti differenti e/o su piattaforme differenti. Se devi fare un deploy tramite chart helm e pensi di avere individuato un problema, puoi comunque riportarcelo per avere supporto.

2. I logs vengono scritti sulla directory **/var/log/govway** che risulta locale al container a meno che non venga montato un volume su quel path. Se hai bisogno di inviare informazioni di tracciamento su un servizio esterno puoi provare a vedere se fà al caso tuo la fuzionalità di [filetrace](https://govway.org/documentazione/console/avanzate/fileTrace/index.html). In questo caso ti dovrebbe bastare creare i files di configurazione e montarli nel container sotto il path **/etc/govway**
