### ISSUE TITLE
govway3.3.11 warning in fase di avvio per MultimapBuilder.MultimapBuilderWithKeys in guava-31.1-jre.jar

### ISSUE THREAD

**Issue by ilkosta** [link-it/govway-docker#9]
Buongiorno,

durante la fase di avvio dell'immagine inkitaly/govway:3.3.11_postgres, vengono sollevati dei warning relativi a 

```
[org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0003: Could not index class com/google/common/collect/MultimapBuilder$MultimapBuilderWithKeys$2.class at /content/govway.ear/lib/gu
ava-31.1-jre.jar: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0 
```

**Comment by marklar79** [comment]
Buongiorno

I warning segnalati vengono emessi da wildfly in fase di deploy e sono completamente innocui.
Anche se non sono un  problema, a breve modificheremo le immagini rilasciate aggiornando la versione di wildfly utilizzatta alla 26.1.3 e questo dovrebbe anche evitare l'emissione dei messaggi.
